### PR TITLE
feat: support for running the latest version of editor locally

### LINKED ISSUE #700: Run an instance of Libero Editor Locally.
# Description

At the moment, there isn't any really clear instructions for a user on how they can run Libero Editor either locally on their own machine or on another system that they have access to. This means that when somebody [stumbles across the pinned repo for Editor](https://github.com/libero/editor), there isn't any instructions that they can follow to easily run and play with the Editor.

# Tasks
- [ ] Add a docker-compose file that can be used to bring up a local instance of Libero Editor with some test content.
- [ ] Update the README.md file to include some quick start instructions.

# DoD
- [ ] User can clone the [libero/editor](https://github.com/libero/editor), follow the quick start instructions and locally run an instance of Libero Editor.

### PR DESCRIPTION
**Pull request by NuclearRedeye**
Add instructions and support to allow anybody to run the latest version of the editor locally.

This fixes libero/editor#700

### CODE REVIEW

**Comment by NuclearRedeye** [comment]
@Cooryd I've ported over my previous work for running the latest version of Libero Editor locally and put it up onto this draft PR. It's pretty much all working, but images won't load in the Editor. This is because the request for the asset responds with a redirect, and I can't help but wonder if it should be transparently proxying the request instead. Thoughts?

Just to expand a little, if you run `docker-compose up` and then...

```
http://localhost:4000/api/v1/articles/54296/assets/elife-54296-fig1.jpeg
```

You get...

```
http://editor-localstack:4566/s3-editor-destination-bucket/54296/67b7df04-d43b-47d7-8db0-7abb2f3b46c9/elife-54296-fig1.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=key%2F20210304%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20210304T192339Z&X-Amz-Expires=3600&X-Amz-Signature=9d5d19fcddf9d34b5cd0c4b44ed99a68ac9f57029b932bdbc4045a877ee6135d&X-Amz-SignedHeaders=host
```

Which in this instance won't work, as the host name 'editor-localstack' is only valid inside the container network. Changing to...

```
http://localhost:4566/s3-editor-destination-bucket/54296/67b7df04-d43b-47d7-8db0-7abb2f3b46c9/elife-54296-fig1.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=key%2F20210304%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20210304T192339Z&X-Amz-Expires=3600&X-Amz-Signature=9d5d19fcddf9d34b5cd0c4b44ed99a68ac9f57029b932bdbc4045a877ee6135d&X-Amz-SignedHeaders=host
```

Does work fine.

**Comment by Cooryd** [comment]
So we encountered this issue when working with article-store a while back and came up with a hack-y but working solution.

We set the `editor-article-store` container to share the `localstack` network `network_mode: "service:localstack"`
https://github.com/libero/editor-article-store/blob/master/docker-compose.yaml#L10

We don't expose any `editor-article-store` ports in the `editor-article-store` docker-compose config block, instead we now expose its ports through the use of the `localstack`port mappin config https://github.com/libero/editor-article-store/blob/a7b546d705177589369f00f2ac0e020fb096677d/docker-compose.yaml#L15

**Comment by NuclearRedeye** [comment]
@Cooryd Cheers, if it's OK i'll follow up with looking into making those adjustments. I'd like to have something committed in advance of the SIG meeting today just in case any of them want to immediately test it.

**Comment by NuclearRedeye** [comment]
Found a better solution to the image issue. The web server simply needed some extra configuration to rewrite response headers so that internal hostnames only valid on the container network are rewritten to hostnames that are valid externally. Overall much  cleaner I think and keeps the docker configuration simpler.

**Review by Cooryd — APPROVED** [review]

**Pull request merged**
